name: 🐞 Bug report
description: Create a report to help us improve
labels: [bug]
body:
  - type: textarea
    id: background
    attributes:
      label: Description
      description: Please share a clear and concise description of the problem.
      placeholder: Description
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: Reproduction Steps
      description: |
        Please include minimal steps to reproduce the problem if possible. Attach or link a project if you have one, even if it is very simple. It helps to quickly evaluate and diagnose the issue and ensures any fix addresses your scenario. If you cannot attach a project, include the smallest possible code snippet, with steps to run it. If possible include text as text rather than screenshots (so it shows up in searches).
      placeholder: Minimal Reproduction
    validations:
      required: true
  - type: textarea
    id: log
    attributes:
      label: Log
      description: Please don't submit issue w/o debug log, and preferably from the time the problem occurred!
      placeholder: Attach the debug log as a file or using the 'code' formatting
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      placeholder: "24.12.22"
    validations:
      required: true
  - type: input
    id: version_core
    attributes:
      label: Home Assistant Core Version
      placeholder: "2024.12.5"
    validations:
      required: true
  - type: input
    id: version_haos
    attributes:
      label: Home Assistant Operating System Version
      placeholder: "14.1"
    validations:
      required: true
